FROM wnameless/mysql-phpmyadmin

RUN sed -i 's/bind-address=*/#bind-address= 127.0.0.1/g' /etc/mysql/my.cnf

RUN /usr/sbin/mysqld & \
    sleep 10s &&\
    echo "CREATE USER 'root'@'%';\
GRANT ALL PRIVILEGES ON * . * TO  'root'@'%' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;" | mysql


CMD service apache2 start; \
        mysqld_safe